"""connections

Revision ID: 3f77d1c5c5b0
Revises: ffdc0a98111c
Create Date: 2023-03-02 19:48:37.651941

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = '3f77d1c5c5b0'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connections',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('connection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connection_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    
    if environment == "production":
        op.execute(f"ALTER TABLE connections SET SCHEMA {SCHEMA};")


def downgrade():
    op.drop_table('connections')
    # ### end Alembic commands ###